Add new rule print-versions: create an HTML file of all pkgs and their current versions. File is crumbs/packageVersions.html.

diff --git a/distrib/build/Makefile b/distrib/build/Makefile
--- a/distrib/build/Makefile
+++ b/distrib/build/Makefile
@@ -79,6 +79,8 @@ default:
 	@echo "  reprep-final      Prepare to rebuild final stage *only*."
 	@echo "  package           Clean, archive sources, pre-fetch tarballs, build,"
 	@echo "                    and make media with matching source tarball."
+	@echo "  print-versions    Create crumbs/packageVersions.html to ease finding"
+	@echo "                    newer versions of upstream packages."
 	@echo
 	@echo "Help:"
 	@echo "  help-arch         How to select a different 32-bit ARCH"
@@ -313,6 +315,16 @@ packageinfos.html:
 	fi
 	-$(MAKE) -C sources/modules packageinfos.html
 	@echo "</ul>" >>/tmp/packageinfo.html
+
+# Print all package version/source info
+#
+print-versions:
+	@cd sources; \
+	for I in */; do \
+	  echo -n "$$I " >&2; pushd $$I >/dev/null 2>&1; make --no-print-directory print-version || echo "$$I||print-version failed||" ; popd >/dev/null 2>&1; \
+	done | (echo "<html><body><table>" ; while read PKG VER BASE_URL ; do \
+	  echo "<tr><td style='text-align:right'>$${PKG}</td><td>$$VER</td><td>$$BASE_URL</td></tr>"; \
+	done | sort -f; echo "</table></body></html>") > ../crumbs/packageVersions.html
 
 # Prepare to rebuild the final stage
 reprep-final:
