Tweak main makefile to fail when get-snort-ver.sh can't get version or URL for daq/snort.

diff --git a/distrib/build/Makefile b/distrib/build/Makefile
--- a/distrib/build/Makefile
+++ b/distrib/build/Makefile
@@ -271,6 +271,11 @@ predownload:
 	          echo -e "\n$$I predownload failed.\n"; \
 	          exit 1; \
 	        fi \
+	      else \
+		if [ $$I == "./daq" -o $$I == "./snort" ]; then \
+		  echo -e "\ntoolcrib/get-snort-ver.sh could not get current $${I/.\//} version or URL" >&2; \
+		  exit 1; \
+		fi \
 	      fi \
 	    fi; \
 	  done \
