Yet Another Try. One day, I'll stub my toe on the right incantation.

diff --git a/distrib/build/sources/media/runtimeroot/etc/runt-init b/distrib/build/sources/media/runtimeroot/etc/runt-init
--- a/distrib/build/sources/media/runtimeroot/etc/runt-init
+++ b/distrib/build/sources/media/runtimeroot/etc/runt-init
@@ -40,11 +40,38 @@ test -e /etc/modules && egrep -v "^$|^#" /etc/modules | while read a; do modprob
 
 # Brute-force create harddisk links if udev didn't; this should fix many SCSI/RAID
 #   logical drives.
-if [ -e /dev/sda4 -a ! -e /dev/harddisk4 ]; then
-    for i in "" 1 2 3 4; do
-    ln -s -f /dev/sda$i /dev/harddisk$i
-  done
-fi
+# Also, SCSI RAID apparently can take some time to become ready, so try for 15 seconds.
+typeset -i i; i=0
+while true; do
+
+  # Feedback after one second
+  if [ $i -eq 10 ]; then
+    echo "Waiting for storage to become ready..."
+  fi
+
+  # If the partition node is available but the harddisk symlink isn't,
+  #   make all of the symlinks and bust out.
+  if [ -e "/dev/sda4" ]; then
+    # Wait a /12 second, in case udev is about to do it
+    sleep .5
+    if [ ! -e "/dev/harddisk4" ]; then
+      for NODE in /dev/sda*; do
+        ln -s -f $NODE ${NODE/sda/harddisk}
+      done
+    fi
+    # Either way, the symlink(s) now exist
+    break;
+  fi
+
+  sleep .1
+  i=i+1
+  # 15 seconds should be plenty long enough for SCSI to come to life
+  if [ $i -eq 150 ]; then
+    echo "Could not find root storage device. Cannot boot!"
+    sleep 2
+    exit 1
+  fi
+done
 
 # Switch to hard drive and start the system
 /bin/mount /harddisk -o ro
